# Generated by Django 4.0.9 on 2023-02-10 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('airspace', '0003_alter_flight_aircraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateTimeField()),
                ('airport_name', models.CharField(max_length=255)),
                ('no_flights', models.IntegerField()),
                ('aircraft_stats', models.JSONField()),
            ],
            options={
                'verbose_name': 'Flight Report',
                'verbose_name_plural': 'Flight Reports',
            },
        ),
    ]
